// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module seq_align_multiple_seq_align_Pipeline_VITIS_LOOP_78_1_VITIS_LOOP_79_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        dp_matrix_V_address0,
        dp_matrix_V_ce0,
        dp_matrix_V_we0,
        dp_matrix_V_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [15:0] dp_matrix_V_address0;
output   dp_matrix_V_ce0;
output   dp_matrix_V_we0;
output  [8:0] dp_matrix_V_d0;

reg ap_idle;
reg dp_matrix_V_ce0;
reg dp_matrix_V_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln78_fu_106_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [0:0] select_ln78_2_fu_177_p3;
reg   [0:0] select_ln78_2_reg_245;
wire    ap_block_pp0_stage0_11001;
reg   [15:0] dp_matrix_V_addr_reg_249;
wire   [63:0] zext_ln81_1_fu_195_p1;
wire    ap_block_pp0_stage0;
reg   [10:0] rr_fu_50;
wire   [10:0] add_ln79_fu_200_p2;
wire    ap_loop_init;
reg   [10:0] pp_fu_54;
wire   [10:0] select_ln78_1_fu_141_p3;
reg   [20:0] indvar_flatten_fu_58;
wire   [20:0] add_ln78_1_fu_112_p2;
wire   [3:0] empty_fu_96_p1;
wire   [0:0] icmp_ln79_fu_127_p2;
wire   [10:0] add_ln78_fu_121_p2;
wire   [5:0] p_cast_mid2_v_fu_149_p4;
wire   [3:0] empty_20_fu_167_p1;
wire   [0:0] cond236_mid1_fu_171_p2;
wire   [0:0] cond236_fu_100_p2;
wire   [10:0] select_ln78_fu_133_p3;
wire   [15:0] tmp_fu_159_p3;
wire   [15:0] zext_ln81_fu_185_p1;
wire   [15:0] add_ln81_fu_189_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

seq_align_multiple_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_58 <= 21'd0;
        end else if (((icmp_ln78_fu_106_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten_fu_58 <= add_ln78_1_fu_112_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            pp_fu_54 <= 11'd0;
        end else if (((icmp_ln78_fu_106_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            pp_fu_54 <= select_ln78_1_fu_141_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            rr_fu_50 <= 11'd0;
        end else if (((icmp_ln78_fu_106_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            rr_fu_50 <= add_ln79_fu_200_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln78_fu_106_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        dp_matrix_V_addr_reg_249 <= zext_ln81_1_fu_195_p1;
        select_ln78_2_reg_245 <= select_ln78_2_fu_177_p3;
    end
end

always @ (*) begin
    if (((icmp_ln78_fu_106_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        dp_matrix_V_ce0 = 1'b1;
    end else begin
        dp_matrix_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((select_ln78_2_reg_245 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        dp_matrix_V_we0 = 1'b1;
    end else begin
        dp_matrix_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln78_1_fu_112_p2 = (indvar_flatten_fu_58 + 21'd1);

assign add_ln78_fu_121_p2 = (pp_fu_54 + 11'd1);

assign add_ln79_fu_200_p2 = (select_ln78_fu_133_p3 + 11'd1);

assign add_ln81_fu_189_p2 = (tmp_fu_159_p3 + zext_ln81_fu_185_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign cond236_fu_100_p2 = ((empty_fu_96_p1 == 4'd0) ? 1'b1 : 1'b0);

assign cond236_mid1_fu_171_p2 = ((empty_20_fu_167_p1 == 4'd0) ? 1'b1 : 1'b0);

assign dp_matrix_V_address0 = dp_matrix_V_addr_reg_249;

assign dp_matrix_V_d0 = 9'd0;

assign empty_20_fu_167_p1 = add_ln78_fu_121_p2[3:0];

assign empty_fu_96_p1 = pp_fu_54[3:0];

assign icmp_ln78_fu_106_p2 = ((indvar_flatten_fu_58 == 21'd1048576) ? 1'b1 : 1'b0);

assign icmp_ln79_fu_127_p2 = ((rr_fu_50 == 11'd1024) ? 1'b1 : 1'b0);

assign p_cast_mid2_v_fu_149_p4 = {{select_ln78_1_fu_141_p3[9:4]}};

assign select_ln78_1_fu_141_p3 = ((icmp_ln79_fu_127_p2[0:0] == 1'b1) ? add_ln78_fu_121_p2 : pp_fu_54);

assign select_ln78_2_fu_177_p3 = ((icmp_ln79_fu_127_p2[0:0] == 1'b1) ? cond236_mid1_fu_171_p2 : cond236_fu_100_p2);

assign select_ln78_fu_133_p3 = ((icmp_ln79_fu_127_p2[0:0] == 1'b1) ? 11'd0 : rr_fu_50);

assign tmp_fu_159_p3 = {{p_cast_mid2_v_fu_149_p4}, {10'd0}};

assign zext_ln81_1_fu_195_p1 = add_ln81_fu_189_p2;

assign zext_ln81_fu_185_p1 = select_ln78_fu_133_p3;

endmodule //seq_align_multiple_seq_align_Pipeline_VITIS_LOOP_78_1_VITIS_LOOP_79_2
